### PR TITLE
An BindingException exception occurs when starting dss-framework-project-serve #423

### PR DESCRIPTION
**Pull request by jiyegege**
Solve org.apache.ibatis.binding.BindingException. Invalid binding
statement (not found) exception.
For more information, see：
#423

### CODE REVIEW

**Review by wushengyeyouya — COMMENTED** [review]
Hi, can you resubmit this PR to dev-dataModelCenter branch?

**Comment by jiyegege** [comment]
> Hi, can you resubmit this PR to dev-dataModelCenter branch?

ok

**Comment by jiyegege** [comment]
> Hi, can you resubmit this PR to dev-dataModelCenter branch?

ok，i changed

**Review by wushengyeyouya — APPROVED** [review]
LGTM.

**Pull request merged**
