### PR TITLE
[Feature] Scripts jdbc 多数据源切换 

### PR DESCRIPTION
**Pull request by yhdup**
https://github.com/WeBankFinTech/DataSphereStudio/issues/940

### CODE REVIEW

**Review by demonray — CHANGES_REQUESTED** [review]
1. Private configuration for `.env ` does not need to be submitted 
2. The request of 'data-source-manager/info' in `container.vue`  need backend service？

Does everyone need this feature, It is recommended to develop as a plug-in.  eg: https://github.com/WeDataSphere/DataSphereStudio/tree/dev-1.1.7/web/packages/exts/

**Review by jacktao007 — APPROVED** [review]
LGTM.

**Comment by FourSpaces** [comment]
现在选择数据源的功能是啥状态呢?  后续版本有上线的可能么?

**Comment by lglfa** [comment]
> 

there should be mutiple jdbc connection for big data service such as hiveserver2, presto, trino, kylin, mysql. this is a necessary feature

**Review by demonray — APPROVED** [review]

**Review by zqburde — APPROVED** [review]
LGTM

**Pull request merged**
